runtime: nodejs20
env: standard

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|ico|txt|json|woff|woff2|ttf|eot|svg))$
    static_files: frontend-dist/\1
    upload: frontend-dist/.*\.(gif|png|jpg|css|js|ico|txt|json|woff|woff2|ttf|eot|svg)$
    secure: always

  - url: /.*
    static_files: frontend-dist/index.html
    upload: frontend-dist/index.html
    secure: always

env_variables:
  NODE_ENV: "production" 