runtime: python39
instance_class: F1

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

env_variables:
  PYTHONUNBUFFERED: "true"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto
  secure: always 